# Generated by Django 2.0.8 on 2018-10-29 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_character'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
