# Generated by Django 2.0.8 on 2018-12-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_make_character_name_unique_per_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year_began',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='year_ended',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
