# Generated by Django 2.0.8 on 2018-12-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_anime_make_year_ended_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='year_ended',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
